[package]
name = "online-group-trivia-server"
version = "0.1.0"
authors = ["Eden <edenyefet@gmail.com>"]
edition = "2018"

[[bin]]
name = "app"
path = "server/src/main.rs"

[workspace]
members = [
    "websocket",
    "interfaces",
    "database",
    "pub-sub",
    "server"
]
