[package]
name = "interfaces"
version = "0.1.0"
edition = "2018"

[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }
serde_json = "1.0"
serde = { version = "1.0.120", features = ["derive"] }
